name: learn-github-actions
on: [push]
jobs:
  anchor-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
          override: true
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: sh -c "$(curl -sSfL https://release.solana.com/v1.10.8/install)"
      - name: Install yarn
      - run: npm install -g yarn
      - run: npm i -g @project-serum/anchor-cli
      - run: anchor test